### ISSUE TITLE
借地方请教一下

### ISSUE THREAD

**Issue by longforus** [enbandari/Android-LuaJavax#1]
不知道怎么好联系您,关于gradle转kts有2个地方想请教一下:
1.调用其他gradle文件里面的方法:
在app.gradle中定义了:
```groovy
plugins{
    id 'com.android.application'
}
apply from: "jiaguMac.gradle.kts"
def isTinkerTask(){
    return gradle.startParameter.taskNames.toString().toUpperCase().contains('TINKER')
}
```
如何在其他的jiaguMac.gradle.kts文件中调用到呢?

2. jiaguMac.gradle.kts的这段如何改写:
``` kotlin
afterEvaluate {
    if (isTinkerTask()) {
        println("是tinker的task退出加固task")
        return
    }
    project.tasks.findAll {
        if (it.name.startsWith("assemblePhone") && it.name.endsWith("Release")) {
            it.doLast {
                android.applicationVariants.all { variant ->
                    if (variant.buildType.name == "release" && variant.getProductFlavors()[0].getName() == "phone") {
                        //since gradle 6.5 above
                        //                        def folder = variant.getPackageApplicationProvider().get().outputDirectory.asFile.get()
                        def folder = variant . getPackageApplicationProvider ().get().outputDirectory
                        println(folder)
                        variant.outputs.each { out ->
                            def outputFile = out . outputFile
                                if (outputFile != null && outputFile.name.endsWith(".apk")) {
                                    //do something
                                }
                        }
                    }
                }
            }
        }
    }
}
```

非常感谢

**Comment by bennyhuo** [comment]
建议将这个方法定义到 buildSrc 当中。原理相关内容可以参考我博客 www.bennyhuo.com 里面定义扩展的文章，配套视频预计在5.2发布。

--------------原始邮件--------------
发件人："Void Young ***@***.***&gt;;
发送时间：2021年4月19日(星期一) 上午10:36
收件人："bennyhuo/Android-LuaJavax" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[bennyhuo/Android-LuaJavax] 借地方请教一下 (#1)
-----------------------------------

 

 
不知道怎么好联系您,关于gradle转kts有2个地方想请教一下:
 1.调用其他gradle文件里面的方法:
 在app.gradle中定义了:
 plugins{     id 'com.android.application' } apply from: "jiaguMac.gradle.kts" def isTinkerTask(){     return gradle.startParameter.taskNames.toString().toUpperCase().contains('TINKER') }
 
如何在其他的jiaguMac.gradle.kts文件中调用到呢?
  
jiaguMac.gradle.kts的这段如何改写:
  afterEvaluate {     if (isTinkerTask()) {         println("是tinker的task退出加固task")         return     }     project.tasks.findAll {         if (it.name.startsWith("assemblePhone") &amp;&amp; it.name.endsWith("Release")) {             it.doLast {                 android.applicationVariants.all { variant -&gt;                     if (variant.buildType.name == "release" &amp;&amp; variant.getProductFlavors()[0].getName() == "phone") {                         //since gradle 6.5 above                         //                        def folder = variant.getPackageApplicationProvider().get().outputDirectory.asFile.get()                         def folder = variant . getPackageApplicationProvider ().get().outputDirectory                         println(folder)                         variant.outputs.each { out -&gt;                             def outputFile = out . outputFile                                 if (outputFile != null &amp;&amp; outputFile.name.endsWith(".apk")) {                                     //do something                                 }                         }                     }                 }             }         }     } }
 
非常感谢

**Comment by longforus** [comment]
好的 非常感谢
